BEGIN;

CREATE OR REPLACE FUNCTION app.enforce_legal_document_version()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  IF TG_OP = 'DELETE' THEN
    RAISE EXCEPTION 'LEGAL_DOCUMENT_HARD_DELETE_NOT_ALLOWED' USING ERRCODE = '42501';
  END IF;

  IF TG_OP = 'INSERT' THEN
    IF NOT app.is_admin() THEN
      RAISE EXCEPTION 'LEGAL_DOCUMENT_ADMIN_REQUIRED' USING ERRCODE = '42501';
    END IF;
    RETURN NEW;
  END IF;

  IF NOT app.is_admin() THEN
    RAISE EXCEPTION 'LEGAL_DOCUMENT_ADMIN_REQUIRED' USING ERRCODE = '42501';
  END IF;

  IF NEW.id IS DISTINCT FROM OLD.id
     OR NEW.document_type IS DISTINCT FROM OLD.document_type
     OR NEW.locale IS DISTINCT FROM OLD.locale
     OR NEW.version IS DISTINCT FROM OLD.version
     OR NEW.created_by IS DISTINCT FROM OLD.created_by
     OR NEW.created_at IS DISTINCT FROM OLD.created_at THEN
    RAISE EXCEPTION 'LEGAL_DOCUMENT_IDENTITY_IMMUTABLE' USING ERRCODE = '23514';
  END IF;

  IF OLD.status IN ('ACTIVE', 'RETIRED') AND (
    NEW.title IS DISTINCT FROM OLD.title
    OR NEW.content_markdown IS DISTINCT FROM OLD.content_markdown
    OR NEW.content_sha256 IS DISTINCT FROM OLD.content_sha256
  ) THEN
    RAISE EXCEPTION 'LEGAL_DOCUMENT_PUBLISHED_CONTENT_IMMUTABLE' USING ERRCODE = '23514';
  END IF;

  IF NOT (
    (OLD.status = 'DRAFT' AND NEW.status IN ('DRAFT', 'ACTIVE', 'RETIRED'))
    OR (OLD.status = 'ACTIVE' AND NEW.status IN ('ACTIVE', 'RETIRED'))
    OR (OLD.status = 'RETIRED' AND NEW.status = 'RETIRED')
  ) THEN
    RAISE EXCEPTION 'LEGAL_DOCUMENT_STATUS_TRANSITION_NOT_ALLOWED' USING ERRCODE = '23514';
  END IF;

  IF OLD.review_status = 'PROFESSIONAL_REVIEWED'
     AND NEW.review_status <> 'PROFESSIONAL_REVIEWED' THEN
    RAISE EXCEPTION 'LEGAL_DOCUMENT_REVIEW_CANNOT_BE_REVOKED' USING ERRCODE = '23514';
  END IF;

  IF OLD.review_status = 'PROFESSIONAL_REVIEWED' AND (
    NEW.reviewed_by IS DISTINCT FROM OLD.reviewed_by
    OR NEW.reviewed_at IS DISTINCT FROM OLD.reviewed_at
  ) THEN
    RAISE EXCEPTION 'LEGAL_DOCUMENT_REVIEW_EVIDENCE_IMMUTABLE' USING ERRCODE = '23514';
  END IF;

  RETURN NEW;
END;
$$;

CREATE TRIGGER legal_documents_enforce_version
BEFORE INSERT OR UPDATE OR DELETE ON legal_documents
FOR EACH ROW EXECUTE FUNCTION app.enforce_legal_document_version();

COMMIT;
